"""PNG / WebP 带真实元数据（eXIf / tEXt-AI / EXIF / XMP）的剥离测试。"""

import io
import os
import struct
import sys
import tempfile
import zlib

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import piexif
from PIL import Image

from app.core import cleaner, formats, scanner
from app.core.cleaner import Plan


def png_chunk(ctype, data):
    return struct.pack(">I", len(data)) + ctype + data + struct.pack(">I", zlib.crc32(ctype + data) & 0xFFFFFFFF)


def sp(p, chunks):
    d = open(p, "rb").read()
    assert d[:8] == b"\x89PNG\r\n\x1a\n"
    iend = d.rfind(b"IEND") - 4  # IEND 块起始（长度字段处），在其前插入新块
    return d[:iend] + b"".join(chunks) + d[iend:]


def webp_chunk(four, data):
    return four + struct.pack("<I", len(data)) + data + (b"\x00" if len(data) & 1 else b"")


def exif_bytes():
    raw = piexif.dump({"0th": {271: b"CameraX", 306: b"2026:01:01 00:00:00"},
                       "Exif": {}, "GPS": {}, "Interop": {}, "1st": {}, "thumbnail": None})
    return raw[6:] if raw.startswith(b"Exif\x00\x00") else raw


def test_png():
    with tempfile.TemporaryDirectory() as td:
        pp = os.path.join(td, "p.png")
        Image.new("RGB", (40, 30), (1, 2, 3)).save(pp, "PNG")
        chunks = [png_chunk(b"eXIf", exif_bytes()),
                  png_chunk(b"tEXt", b"Title\x00Photo"),
                  png_chunk(b"tEXt", b"AI-Tool\x00Generated by Midjourney")]
        spliced = sp(pp, chunks)
        open(pp, "wb").write(spliced)
        fs = scanner.scan_file(pp)
        assert fs.ok, fs.error
        plan = Plan(remove={it.key for it in fs.items if it.default_remove})
        data = open(pp, "rb").read()
        parsed = formats.parse(data)
        out, res = cleaner.apply_plan(data, parsed, plan)
        assert res.ok and res.payload_ok, (res.error, res.verify_note)
        Image.open(io.BytesIO(out)).load()
        p2 = os.path.join(td, "p2.png")
        open(p2, "wb").write(out)
        fs2 = scanner.scan_file(p2)
        rem = {it.key for it in fs2.items}
        assert not any(k.startswith("blk:eXIf") for k in rem), "PNG eXIf 未移除"
        assert not any(it.category == "ai" for it in fs2.items), "PNG AI 文本未移除"
        print(f"[PNG]  OK 移除 {res.removed_items} 项 | {res.verify_note} | {len(data)}→{len(out)}")


def test_webp():
    with tempfile.TemporaryDirectory() as td:
        wp = os.path.join(td, "w.webp")
        Image.new("RGB", (40, 30), (4, 5, 6)).save(wp, "WEBP")
        wdata = open(wp, "rb").read()
        xmp = b"http://ns.adobe.com/xap/1.0/\x00" + \
              b'<x:xmpmeta><rdf:RDF><rdf:Description DigitalSourceType="ai"/></rdf:RDF></x:xmpmeta>'
        new = wdata[:12] + webp_chunk(b"EXIF", exif_bytes()) + webp_chunk(b"XMP ", xmp) + wdata[12:]
        open(wp, "wb").write(new)
        fs = scanner.scan_file(wp)
        assert fs.ok, fs.error
        plan = Plan(remove={it.key for it in fs.items if it.default_remove}, xmp_ai=True)
        data = open(wp, "rb").read()
        parsed = formats.parse(data)
        out, res = cleaner.apply_plan(data, parsed, plan)
        assert res.ok and res.payload_ok, (res.error, res.verify_note)
        Image.open(io.BytesIO(out)).load()
        p3 = os.path.join(td, "w2.webp")
        open(p3, "wb").write(out)
        fs2 = scanner.scan_file(p3)
        rem = {it.key for it in fs2.items}
        assert not any(k.startswith("blk:EXIF") for k in rem), "WebP EXIF 未移除"
        assert not any(it.category == "ai" for it in fs2.items), "WebP AI 未移除"
        print(f"[WEBP] OK 移除 {res.removed_items} 项 | {res.verify_note} | {len(data)}→{len(out)}")


if __name__ == "__main__":
    test_png()
    test_webp()
    print("\nPNG/WebP 带元数据测试通过 ✓")
